# Usa la imagen oficial de PostgreSQL como base
FROM postgres:16

# Copia un script SQL de inicialización (opcional)
# COPY init.sql /docker-entrypoint-initdb.d/

# Expone el puerto 5432
EXPOSE 6432

